# Generated by Django 5.2.17 on 2026-09-01 04:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=64)),
                ('license_expiry', models.DateField()),
                ('phone', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_route', 'On route'), ('off_duty', 'Off duty'), ('suspended', 'Suspended')], default='available', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routepilot_driver_profile', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='dispatch.organization')),
            ],
            options={
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('dispatcher', 'Dispatcher'), ('driver', 'Driver'), ('viewer', 'Viewer')], default='viewer', max_length=12)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routepilot_membership', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dispatch.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('contact_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='dispatch.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=24)),
                ('pickup_address', models.TextField(max_length=600)),
                ('delivery_address', models.TextField(max_length=600)),
                ('package_description', models.CharField(max_length=240)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=9)),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('urgent', 'Urgent')], default='standard', max_length=10)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('failed', 'Delivery failed'), ('cancelled', 'Cancelled')], default='unassigned', max_length=12)),
                ('scheduled_pickup', models.DateTimeField()),
                ('delivery_deadline', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_reference', models.CharField(blank=True, max_length=120)),
                ('proof_note', models.TextField(blank=True, max_length=1000)),
                ('failure_reason', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_routepilot_shipments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='dispatch.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='dispatch.organization')),
            ],
            options={
                'ordering': ['delivery_deadline', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('failed', 'Delivery failed'), ('cancelled', 'Cancelled')], max_length=12)),
                ('message', models.CharField(max_length=500)),
                ('visible_to_customer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routepilot_shipment_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_events', to='dispatch.organization')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dispatch.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('bike', 'Cargo bike'), ('van', 'Delivery van'), ('truck', 'Box truck'), ('refrigerated', 'Refrigerated truck')], max_length=14)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_route', 'On route'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', max_length=12)),
                ('odometer_km', models.PositiveIntegerField(default=0)),
                ('next_service_km', models.PositiveIntegerField(default=10000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='dispatch.organization')),
            ],
            options={
                'ordering': ['registration'],
            },
        ),
        migrations.CreateModel(
            name='DispatchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routepilot_assignments', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='dispatch.driverprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dispatch.organization')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='dispatch.shipment')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='dispatch.vehicle')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='driverprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'license_number'), name='unique_routepilot_driver_license'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_routepilot_customer_name'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('organization', 'tracking_code'), name='unique_routepilot_tracking_code'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__gt', Decimal('0'))), name='routepilot_shipment_positive_weight'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('organization', 'registration'), name='unique_routepilot_vehicle_registration'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_kg__gt', 0)), name='routepilot_vehicle_positive_capacity'),
        ),
    ]
