# Generated by Django 5.2.17 on 2026-09-08 04:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("OWNER", "Owner"), ("MANAGER", "Privacy manager"), ("ANALYST", "Analyst"), ("VIEWER", "Viewer")],
                        max_length=12,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="privacy_membership", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="privacy.organization"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataSubject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subjects", to="privacy.organization"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tracking_code", models.CharField(editable=False, max_length=24, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ACCESS", "Access"),
                            ("DELETION", "Deletion"),
                            ("CORRECTION", "Correction"),
                            ("PORTABILITY", "Portability"),
                            ("OBJECTION", "Objection"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[
                            ("GDPR", "EU GDPR"),
                            ("UK_GDPR", "UK GDPR"),
                            ("CCPA", "California CCPA"),
                            ("INDIA_DPDP", "India DPDP"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("VERIFYING", "Verifying identity"),
                            ("IN_PROGRESS", "In progress"),
                            ("REVIEW", "Final review"),
                            ("FULFILLED", "Fulfilled"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="RECEIVED",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField()),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_at", models.DateTimeField()),
                ("identity_verified_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_summary", models.TextField(blank=True)),
                ("secure_delivery_reference", models.CharField(blank=True, max_length=120)),
                ("rejection_reason", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="privacy_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="privacy_requests_created", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="requests", to="privacy.organization"),
                ),
                (
                    "subject",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requests", to="privacy.datasubject"),
                ),
            ],
            options={
                "ordering": ["due_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.CharField(max_length=240)),
                ("visible_to_subject", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (
                    "request",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="privacy.privacyrequest"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("due_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(choices=[("OPEN", "Open"), ("WORKING", "Working"), ("DONE", "Done")], default="OPEN", max_length=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="privacy_tasks", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="privacy.privacyrequest"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="datasubject",
            constraint=models.UniqueConstraint(fields=("organization", "email"), name="unique_subject_email_per_org"),
        ),
    ]
