# Generated by Django 5.2.17 on 2026-09-11 04:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("department", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditFinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tracking_code", models.CharField(editable=False, max_length=24, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CONTROL_GAP", "Control gap"),
                            ("POLICY_BREACH", "Policy breach"),
                            ("ACCESS_RISK", "Access risk"),
                            ("EVIDENCE_GAP", "Evidence gap"),
                            ("THIRD_PARTY_RISK", "Third-party risk"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("SOX", "SOX"),
                            ("ISO27001", "ISO 27001"),
                            ("SOC2", "SOC 2"),
                            ("PCI_DSS", "PCI DSS"),
                            ("INTERNAL", "Internal policy"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("TRIAGE", "Triage"),
                            ("REMEDIATION", "Remediation"),
                            ("REVIEW", "Final review"),
                            ("RESOLVED", "Resolved"),
                            ("ACCEPTED_RISK", "Risk accepted"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField()),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_at", models.DateTimeField()),
                ("triaged_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_summary", models.TextField(blank=True)),
                ("evidence_reference", models.CharField(blank=True, max_length=120)),
                ("risk_acceptance_reason", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="audit_findings_created", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "control_area",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="findings", to="audit.controlarea"),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="findings", to="audit.organization"),
                ),
            ],
            options={
                "ordering": ["due_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FindingEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.CharField(max_length=240)),
                ("visible_to_stakeholders", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("finding", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="audit.auditfinding")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("OWNER", "Owner"), ("MANAGER", "Audit manager"), ("ANALYST", "Auditor"), ("VIEWER", "Viewer")],
                        max_length=12,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="audit_membership", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="audit.organization"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="controlarea",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="control_areas", to="audit.organization"),
        ),
        migrations.CreateModel(
            name="RemediationTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("due_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(choices=[("OPEN", "Open"), ("WORKING", "Working"), ("DONE", "Done")], default="OPEN", max_length=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="audit_tasks", to=settings.AUTH_USER_MODEL),
                ),
                ("finding", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="audit.auditfinding")),
            ],
        ),
        migrations.AddConstraint(
            model_name="controlarea",
            constraint=models.UniqueConstraint(fields=("organization", "email"), name="unique_control_area_email_per_org"),
        ),
    ]
