import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("auth", "0012_alter_user_first_name_max_length")]
    operations = [
        migrations.CreateModel(name="Organization", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("slug", models.SlugField(unique=True)), ("created_at", models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="Customer", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("email", models.EmailField(max_length=254)), ("company", models.CharField(blank=True, max_length=120)), ("created_at", models.DateTimeField(auto_now_add=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customers", to="support.organization"))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="Membership", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("role", models.CharField(choices=[("owner", "Owner"), ("agent", "Agent")], default="agent", max_length=12)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="support.organization")), ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="support_membership", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Ticket", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("subject", models.CharField(max_length=180)), ("description", models.TextField(max_length=4000)), ("category", models.CharField(blank=True, max_length=80)), ("status", models.CharField(choices=[("open", "Open"), ("in_progress", "In progress"), ("waiting", "Waiting on customer"), ("resolved", "Resolved")], default="open", max_length=20)), ("priority", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")], default="medium", max_length=12)), ("due_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_tickets", to=settings.AUTH_USER_MODEL)), ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="support.customer")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tickets", to="support.organization"))], options={"ordering": ["-updated_at"]}),
        migrations.CreateModel(name="Reply", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("body", models.TextField(max_length=3000)), ("internal", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="replies", to="support.organization")), ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="replies", to="support.ticket"))], options={"ordering": ["created_at"]}),
        migrations.AddConstraint(model_name="customer", constraint=models.UniqueConstraint(fields=("organization", "email"), name="unique_customer_email_per_org")),
    ]
