# Generated by Django 5.2.17 on 2026-08-28 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('lead', 'QA lead'), ('tester', 'Tester'), ('viewer', 'Viewer')], default='tester', max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_membership', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='qa.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, max_length=1500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('archived', 'Archived')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='qa.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_qa_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_key', models.CharField(max_length=24)),
                ('title', models.CharField(max_length=180)),
                ('requirement_reference', models.CharField(blank=True, max_length=80)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('test_type', models.CharField(choices=[('functional', 'Functional'), ('regression', 'Regression'), ('smoke', 'Smoke'), ('integration', 'Integration'), ('usability', 'Usability')], default='functional', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('deprecated', 'Deprecated')], default='draft', max_length=12)),
                ('preconditions', models.TextField(blank=True, max_length=2000)),
                ('steps', models.TextField(max_length=5000)),
                ('expected_result', models.TextField(max_length=2500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_test_cases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='qa.organization')),
            ],
            options={
                'ordering': ['case_key'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('target_version', models.CharField(max_length=60)),
                ('environment', models.CharField(choices=[('local', 'Local'), ('qa', 'QA'), ('staging', 'Staging'), ('production', 'Production')], default='staging', max_length=12)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='planned', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_test_runs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='qa.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='qa.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_run', 'Not run'), ('passed', 'Passed'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('skipped', 'Skipped')], default='not_run', max_length=10)),
                ('actual_result', models.TextField(blank=True, max_length=2500)),
                ('defect_reference', models.CharField(blank=True, max_length=180)),
                ('evidence_url', models.URLField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_test_executions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='qa.organization')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='qa.testcase')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='qa.testrun')),
            ],
            options={
                'ordering': ['test_case__case_key'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_activities', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_activities', to='qa.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='qa.testrun')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='qa.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='qa.product')),
            ],
            options={
                'ordering': ['product__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='qa.testsuite'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='unique_quality_product_key'),
        ),
        migrations.AddConstraint(
            model_name='testexecution',
            constraint=models.UniqueConstraint(fields=('run', 'test_case'), name='unique_quality_case_per_run'),
        ),
        migrations.AddConstraint(
            model_name='testsuite',
            constraint=models.UniqueConstraint(fields=('organization', 'product', 'name'), name='unique_quality_suite_name'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('organization', 'case_key'), name='unique_quality_case_key'),
        ),
    ]
