import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("auth", "0012_alter_user_first_name_max_length")]
    operations = [
        migrations.CreateModel(name="Organization", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("slug", models.SlugField(unique=True)), ("created_at", models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="Contact", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("company", models.CharField(blank=True, max_length=120)), ("email", models.EmailField(max_length=254)), ("phone", models.CharField(blank=True, max_length=30)), ("created_at", models.DateTimeField(auto_now_add=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contacts", to="crm.organization"))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="Membership", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("role", models.CharField(choices=[("owner", "Owner"), ("member", "Member")], default="member", max_length=12)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="crm.organization")), ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="membership", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Deal", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=160)), ("value", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])), ("stage", models.CharField(choices=[("lead", "Lead"), ("qualified", "Qualified"), ("proposal", "Proposal"), ("won", "Won"), ("lost", "Lost")], default="lead", max_length=20)), ("expected_close", models.DateField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("contact", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deals", to="crm.contact")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deals", to="crm.organization"))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="Activity", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("kind", models.CharField(choices=[("call", "Call"), ("email", "Email"), ("meeting", "Meeting"), ("note", "Note")], max_length=12)), ("notes", models.TextField(max_length=1000)), ("created_at", models.DateTimeField(auto_now_add=True)), ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ("deal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="crm.deal")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="crm.organization"))], options={"ordering": ["-created_at"]}),
        migrations.AddConstraint(model_name="contact", constraint=models.UniqueConstraint(fields=("organization", "email"), name="unique_contact_email_per_org")),
    ]
