import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial=True
    dependencies=[("auth","0012_alter_user_first_name_max_length")]
    operations=[
        migrations.CreateModel(name="Organization",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=120)),("slug",models.SlugField(unique=True)),("created_at",models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="Membership",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("role",models.CharField(choices=[("owner","Owner"),("member","Member")],default="member",max_length=12)),("organization",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="memberships",to="work.organization")),("user",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="work_membership",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Project",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=140)),("code",models.CharField(max_length=12)),("description",models.TextField(blank=True,max_length=1000)),("color",models.CharField(default="#6C5CE7",max_length=7)),("archived",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),("organization",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="projects",to="work.organization"))],options={"ordering":["name"]}),
        migrations.CreateModel(name="Task",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=180)),("description",models.TextField(blank=True,max_length=3000)),("status",models.CharField(choices=[("backlog","Backlog"),("todo","To do"),("doing","In progress"),("review","Review"),("done","Done")],default="backlog",max_length=12)),("priority",models.CharField(choices=[("low","Low"),("medium","Medium"),("high","High"),("urgent","Urgent")],default="medium",max_length=12)),("due_date",models.DateField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("assignee",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="work_tasks",to=settings.AUTH_USER_MODEL)),("organization",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="tasks",to="work.organization")),("project",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="tasks",to="work.project"))],options={"ordering":["-updated_at"]}),
        migrations.CreateModel(name="Comment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("body",models.TextField(max_length=2000)),("created_at",models.DateTimeField(auto_now_add=True)),("author",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL)),("organization",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="comments",to="work.organization")),("task",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="comments",to="work.task"))],options={"ordering":["created_at"]}),
        migrations.AddConstraint(model_name="project",constraint=models.UniqueConstraint(fields=("organization","code"),name="unique_project_code_per_org")),
    ]
