# Generated by Django 5.2.17 on 2026-08-31 04:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('scope', models.TextField(max_length=1800)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_assessments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='risk.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('risk_manager', 'Risk manager'), ('analyst', 'Risk analyst'), ('viewer', 'Viewer')], default='viewer', max_length=14)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_risk_membership', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='risk.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('security', 'Security'), ('privacy', 'Privacy'), ('resilience', 'Resilience'), ('compliance', 'Compliance'), ('governance', 'Governance')], max_length=12)),
                ('question', models.CharField(max_length=320)),
                ('weight', models.PositiveSmallIntegerField(default=3)),
                ('response', models.CharField(blank=True, choices=[('', 'Unanswered'), ('yes', 'Implemented'), ('partial', 'Partially implemented'), ('no', 'Not implemented'), ('na', 'Not applicable')], default='', max_length=8)),
                ('evidence', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True, max_length=1800)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='risk.assessment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_controls', to='risk.organization')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160)),
                ('category', models.CharField(choices=[('cloud', 'Cloud and infrastructure'), ('data', 'Data and analytics'), ('finance', 'Finance and payments'), ('professional', 'Professional services'), ('other', 'Other')], max_length=16)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('under_review', 'Under review'), ('suspended', 'Suspended'), ('offboarded', 'Offboarded')], default='onboarding', max_length=12)),
                ('service_description', models.TextField(max_length=1800)),
                ('handles_personal_data', models.BooleanField(default=False)),
                ('has_production_access', models.BooleanField(default=False)),
                ('has_financial_access', models.BooleanField(default=False)),
                ('annual_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('contract_expiry', models.DateField(blank=True, null=True)),
                ('next_review', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_risk_vendors', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='risk.organization')),
            ],
            options={
                'ordering': ['-criticality', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(max_length=2200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('accepted', 'Risk accepted'), ('resolved', 'Resolved')], default='open', max_length=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, max_length=1800)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='risk.assessment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_findings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='risk.organization')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='risk.vendor')),
            ],
            options={
                'ordering': ['status', '-severity', 'due_date'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='risk.vendor'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_activity', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='risk.assessment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_activity', to='risk.organization')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='risk.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_vendor_risk_slug'),
        ),
    ]
