# Generated by Django 5.2.17 on 2026-09-02 12:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('claims_manager', 'Claims manager'), ('technician', 'Technician'), ('viewer', 'Viewer')], default='viewer', max_length=14)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='returnrelay_membership', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='returns.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('contact_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='returns.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('appliance', 'Appliance'), ('equipment', 'Equipment'), ('furniture', 'Furniture'), ('other', 'Other')], max_length=16)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('warranty_months', models.PositiveSmallIntegerField(default=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='returns.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=80)),
                ('order_reference', models.CharField(max_length=80)),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='returns.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_items', to='returns.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='returns.product')),
            ],
            options={
                'ordering': ['-purchase_date', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='ReturnClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=28)),
                ('issue_category', models.CharField(choices=[('defective', 'Product defect'), ('damaged', 'Damaged in transit'), ('wrong_item', 'Wrong item'), ('performance', 'Performance issue'), ('other', 'Other')], max_length=14)),
                ('description', models.TextField(max_length=2400)),
                ('evidence_url', models.URLField(blank=True)),
                ('requested_remedy', models.CharField(choices=[('repair', 'Repair'), ('replacement', 'Replacement'), ('refund', 'Refund')], max_length=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=8)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('triage', 'In triage'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('awaiting_item', 'Awaiting item'), ('received', 'Item received'), ('inspecting', 'Inspecting'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=14)),
                ('response_due', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, max_length=1400)),
                ('resolution', models.CharField(blank=True, choices=[('repaired', 'Repaired'), ('replaced', 'Replaced'), ('refunded', 'Refunded'), ('store_credit', 'Store credit'), ('no_fault', 'No fault found')], max_length=14)),
                ('resolution_summary', models.TextField(blank=True, max_length=1800)),
                ('resolution_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('replacement_reference', models.CharField(blank=True, max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_returnrelay_claims', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='returns.registereditem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='returns.organization')),
            ],
            options={
                'ordering': ['response_due', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('like_new', 'Like new'), ('used', 'Used'), ('damaged', 'Damaged'), ('severe', 'Severely damaged')], max_length=10)),
                ('fault_confirmed', models.BooleanField(default=False)),
                ('findings', models.TextField(max_length=2200)),
                ('recommendation', models.CharField(choices=[('repair', 'Repair'), ('replace', 'Replace'), ('refund', 'Refund'), ('deny', 'Deny claim'), ('no_fault', 'No fault found')], max_length=10)),
                ('inspected_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returnrelay_inspections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='returns.organization')),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='returns.returnclaim')),
            ],
            options={
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('triage', 'In triage'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('awaiting_item', 'Awaiting item'), ('received', 'Item received'), ('inspecting', 'Inspecting'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=14)),
                ('message', models.CharField(max_length=600)),
                ('visible_to_customer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returnrelay_claim_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_events', to='returns.organization')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='returns.returnclaim')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_returnrelay_customer_name'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('organization', 'sku'), name='unique_returnrelay_product_sku'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('retail_price__gte', 0)), name='returnrelay_nonnegative_retail_price'),
        ),
        migrations.AddConstraint(
            model_name='registereditem',
            constraint=models.UniqueConstraint(fields=('organization', 'serial_number'), name='unique_returnrelay_serial_number'),
        ),
        migrations.AddConstraint(
            model_name='returnclaim',
            constraint=models.UniqueConstraint(fields=('organization', 'tracking_code'), name='unique_returnrelay_claim_tracking'),
        ),
        migrations.AddConstraint(
            model_name='returnclaim',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_amount__gte', 0)), name='returnrelay_nonnegative_resolution_amount'),
        ),
    ]
