import decimal
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [("auth", "0012_alter_user_first_name_max_length")]
    operations = [
        migrations.CreateModel(name="Organization", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("slug", models.SlugField(unique=True)), ("tax_id", models.CharField(blank=True, max_length=40)), ("created_at", models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="Client", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("email", models.EmailField(max_length=254)), ("company", models.CharField(blank=True, max_length=120)), ("address", models.TextField(blank=True, max_length=500)), ("created_at", models.DateTimeField(auto_now_add=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="clients", to="billing.organization"))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="Membership", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("role", models.CharField(choices=[("owner", "Owner"), ("accountant", "Accountant")], default="accountant", max_length=12)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="billing.organization")), ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="billing_membership", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Invoice", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("number", models.CharField(max_length=30)), ("issue_date", models.DateField(default=django.utils.timezone.localdate)), ("due_date", models.DateField()), ("status", models.CharField(choices=[("draft", "Draft"), ("sent", "Sent"), ("paid", "Paid"), ("void", "Void")], default="draft", max_length=12)), ("tax_rate", models.DecimalField(decimal_places=2, default=decimal.Decimal("18.00"), max_digits=5, validators=[django.core.validators.MinValueValidator(0)])), ("notes", models.TextField(blank=True, max_length=1000)), ("created_at", models.DateTimeField(auto_now_add=True)), ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="billing.client")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="billing.organization"))], options={"ordering": ["-issue_date", "-id"]}),
        migrations.CreateModel(name="LineItem", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("description", models.CharField(max_length=200)), ("quantity", models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01"))])), ("unit_price", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])), ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="billing.invoice"))]),
        migrations.CreateModel(name="Payment", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01"))])), ("method", models.CharField(default="Bank transfer", max_length=40)), ("reference", models.CharField(blank=True, max_length=100)), ("paid_on", models.DateField(default=django.utils.timezone.localdate)), ("created_at", models.DateTimeField(auto_now_add=True)), ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="billing.invoice")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="billing.organization"))], options={"ordering": ["-paid_on", "-id"]}),
        migrations.AddConstraint(model_name="client", constraint=models.UniqueConstraint(fields=("organization", "email"), name="unique_client_email_per_org")),
        migrations.AddConstraint(model_name="invoice", constraint=models.UniqueConstraint(fields=("organization", "number"), name="unique_invoice_number_per_org")),
    ]
